### PR TITLE
MCR-2463 Add CLI commands that show messages, properties and resources

### PR DESCRIPTION
**Pull request by toKrause**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2463).

### CODE REVIEW

**Review by rsteph-de — CHANGES_REQUESTED** [review]
This command should go somwhere in mycore-base.
because not everybody uses the mycore-webcli component.

**Comment by toKrause** [comment]
> This command should go somwhere in mycore-base.
> because not everybody uses the mycore-webcli component.

The question is then: Why are the other "Basic Commands" part of `mycore-webcli` and not part of `mycore-base`. The commands `process {0}` and `process resource {0}` are also relevant to non-users of `mycore-webcli`.

Moving the base(ic) commands to another location should be a separate issue.

**Comment by fluetze** [comment]
Should this command be invoked via WebCLI? Might be a security risk, exposes properties containing keys and secrets? We have some commands that can only be used via the shell cli, not web cli. Did you discuss this?

**Comment by toKrause** [comment]
Is this actually a relevant problem? The WebCLI is only available to the special `administrator` user.

**Comment by kkrebs** [comment]
please rename to developer commands and disable per default
should also be part of 2021.06.x

**Comment by toKrause** [comment]
```
First, rewinding head to replay your work on top of it...
Applying: [maven-release-plugin] prepare for next development iteration
Applying: [maven-release-plugin] prepare release v2021.08
Applying: [maven-release-plugin] prepare for next development iteration
Applying: MCR-2463 Add CLI commands that show messages, properties and resources
```

Rebasing from `main` to `2021.06.x` also included the three `[maven-release-plugin] ...` commits that weren't created by me but were already part of `main` but not of `2021.06.x`, .... what to do?

**Comment by sebhofmann** [comment]
Just drop the commits which do not belong to you branch when you rebase.

**Review by kkrebs — APPROVED** [review]

**Review by rsteph-de — APPROVED** [review]
looks good for me

**Pull request merged**
