### PR TITLE
MCR-2131 When replacing a file with an urn in a derivate the urn is r…

### PR DESCRIPTION
**Pull request by chiliego**
…emoved from the derivate xml

[Link to jira](https://mycore.atlassian.net/browse/MCR-).

### CODE REVIEW

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-base/src/main/java/org/mycore/datamodel/metadata/MCRFileMetaEventHandler.java  1
         

Complexity decreasing per file
==============================
+ mycore-base/src/main/java/org/mycore/datamodel/niofs/utils/MCRTreeCopier.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5005440&bid=16513243)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 694f1da90bf914fab67e4e7182defdcc80d374fe! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5260-pull_request-915

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 694f1da90bf914fab67e4e7182defdcc80d374fe! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5260-pull_request-915

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-base/src/main/java/org/mycore/datamodel/metadata/MCRFileMetaEventHandler.java  1
         

Complexity decreasing per file
==============================
+ mycore-base/src/main/java/org/mycore/datamodel/niofs/utils/MCRTreeCopier.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5005440&bid=16513243)

**Review by Possommi — APPROVED** [review]

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-base/src/main/java/org/mycore/datamodel/metadata/MCRFileMetaEventHandler.java  1
         

Complexity decreasing per file
==============================
+ mycore-base/src/main/java/org/mycore/datamodel/niofs/utils/MCRTreeCopier.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5005440&bid=16513243)

**Pull request merged**
