### PR TITLE
MCR-1833 fix adding urn for a single file not working, now throw a ex…

### PR DESCRIPTION
**Pull request by chiliego**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 0e3c1589bbaf4dbf14e561bb40a65279162dff7a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3258-pull_request-586

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 0e3c1589bbaf4dbf14e561bb40a65279162dff7a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3258-pull_request-586

**Review by yagee-de — CHANGES_REQUESTED** [review]
Please make sure to use Eclipse code formatting rules

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on dcb54ff9932285b67a64b21afd08d3cdf13b420f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3290-pull_request-586

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a378ae7b60dcdefa2899eab4fe217b373a7b91bf! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3356-pull_request-586

**Review by yagee-de — APPROVED** [review]

**Pull request merged**
