### PR TITLE
MCR-2065 NPE in MCRNameMerger

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2065).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 88ad1a3aba919c88954fc32da41e6b535e6e9610! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4643-pull_request-819

**Review by fluetze — CHANGES_REQUESTED** [review]
a) Please add a test to MCRTestNameMerger class
b) The method should return false by default, assuming two names are different if not tested otherwise

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on eca026a67fae0f5ad68d109b777862646eaf2357! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4649-pull_request-819

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 5abdee3fc3f972e8e816df430d9f5627ffc3e457! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4651-pull_request-819

**Review by fluetze — APPROVED** [review]

**Pull request merged**
