### PR TITLE
MCR-3041 rest api v 2 quirks

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-3041).

Does not handle yet pretty format on JSON and XML output.

### CODE REVIEW

**Review by rsteph-de — APPROVED** [review]
looks good for me

**Review by Mewel — CHANGES_REQUESTED** [review]
http://localhost:8291/mir/api/v2/objects/xx

Doesn't provide the new X- error codes. The error message is given in the response. But this time not as xml but plain text.

**Comment by yagee-de** [comment]
> http://localhost:8291/mir/api/v2/objects/xx
> 
> Doesn't provide the new X- error codes. The error message is given in the response. But this time not as xml but plain text.

```
$ curl -D - http://localhost:8291/mir/api/v2/objects/xx
HTTP/1.1 400 Bad Request
Server: Jetty(12.0.0)
X-Error-Code: MCROBJECTID_INVALID
X-Error-Message: Invalid ID supplied
X-Error-Time: Wed, 14 Feb 2024 13:31:46 GMT
X-Error-Detail: The ID is not valid: xx , it should match the pattern String_String_Integer
X-Error-UUID: 882b86f0-18cc-4553-91bb-aa5b653bab23
Content-Type: application/xml
Content-Length: 329

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error errorCode="MCROBJECTID_INVALID" timestamp="2024-02-14T13:31:46.027839Z" uuid="882b86f0-18cc-4553-91bb-aa5b653bab23">
    <detail>The ID is not valid: xx , it should match the pattern String_String_Integer</detail>
    <message>Invalid ID supplied</message>
</error>
```

**Review by Mewel — APPROVED** [review]
Looks good!

**Pull request merged**
