### PR TITLE
MCR-2002 EnrichmentResolver leads to open Session

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2002).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 65a03432f5a5eca13f7b28722fec6053020b393e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4205-pull_request-747

**Review by fluetze — APPROVED** [review]
Thank you!

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 65a03432f5a5eca13f7b28722fec6053020b393e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4205-pull_request-747

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 65a03432f5a5eca13f7b28722fec6053020b393e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4205-pull_request-747

**Pull request merged**
