### PR TITLE
MCR-2345 Viewer is sending request for same tiles multiple times

### PR DESCRIPTION
**Pull request by eckstueck**
removed abortLoadingTiles for buffer redraw

[Link to jira](https://mycore.atlassian.net/browse/MCR-2345).

LoadingTiles does not need to be aborted. Because request was already send to Server and the tile might be needed later.
Aborting the tile load has the consequence that the Viewer is sending a request for the same tile multiple times. Especially for the first image, when the viewer ist loading.

### CODE REVIEW

**Comment by sebhofmann** [comment]
It seems like you commit is not linked with your Github profile. Please change your emails to match:
You can show your local settings with:
`$ git config --global user.email
email@example.com`


You can change that Mail with:
`git config user.email "john@doe.org"`

You can find you github mails in Settings > Email

You can change the author auf the last commit with the command:
`git commit --amend --author="John Doe <john@doe.org>"`
You changed a commit you need to push the branch with the -f flag.

https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on cfa81fee45005332770250fe29181e98c6dab796! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6532-pull_request-1162

**Review by yagee-de — APPROVED** [review]
Seems to solve the issue

**Comment by sebhofmann** [comment]
I think there is something other involved, i want to check first.

**Comment by yagee-de** [comment]
The fix is [online](https://www.kulthura.de/suche/p/1/h/1/nc/1.html?tx_jomuseo_pi1009%5BjoDetailView%5D=PPN663966515_0502) and it seems to work. I get like 40 request for a new page and that's more reasonable than the 300-400 before. But we wait with the merge...

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
