### PR TITLE
MCR-2799 support servlet 6.0 container

### PR DESCRIPTION
**Pull request by yagee-de**
update to Servlet 6.0 and Jersey 3.1.0

[Link to jira](https://mycore.atlassian.net/browse/MCR-2799).

### CODE REVIEW

**Review by rsteph-de — APPROVED** [review]
build of a new application worked for me

**Comment by kkrebs** [comment]
We should test if this run in tomcat 10.1.x and also in tomcat 10.0.x before merging

**Comment by Possommi** [comment]
Both tomcat 10.0.27 and 10.1.2 are working just fine (tested with Collections and mycore version 2022.06.1-SNAPSHOT)

**Comment by kkrebs** [comment]
Should not be part of 2022.06.1

**Comment by Possommi** [comment]
> Should not be part of 2022.06.1

but tomcat 10.0.x is EOL

**Comment by rsteph-de** [comment]
> but tomcat 10.0.x is EOL

We know, the merge goes right into the LTS-branch after the release.

**Review by rsteph-de — APPROVED** [review]
ready to bem merged

**Review by Possommi — APPROVED** [review]

**Pull request merged**
