### PR TITLE
MCR-2990 Added support of <xinclude @uri="..."/> element.

### PR DESCRIPTION
**Pull request by Possommi**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2990).

### CODE REVIEW

**Comment by fluetze** [comment]
Maybe we should improve the implementation and use/introduce a namespace for xinclude here.

**Review by fluetze — CHANGES_REQUESTED** [review]
Maybe we should improve the implementation and use/introduce a namespace for xinclude here?

**Comment by Possommi** [comment]
> Maybe we should improve the implementation and use/introduce a namespace for xinclude here?

like ```mcrwebpage:xinclude``` but I think it is not needed since other elements do not have namespaces either

**Comment by fluetze** [comment]
> > Maybe we should improve the implementation and use/introduce a namespace for xinclude here?
> 
> like `mcrwebpage:xinclude` but I think it is not needed since other elements do not have namespaces either

Would help distinguish it from the "official" xinclude, and from the (x)html namespace.

**Review by fluetze — APPROVED** [review]

**Pull request merged**
