### PR TITLE
Issues/mcr 1917 mcr ql condition parser problem

### PR DESCRIPTION
**Pull request by bt1cu**
[Link to jira](https://mycore.atlassian.net/browse/MCR-1917).
Fix bug and add some JUnit tests.
By the way move a static query method from mycore-base to the mycore-solr search, cause it is SOLR specific.

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 6c994d4958ddd035d58b97785c588373856f32ed! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3780-pull_request-663

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on f797d307b0b5176f347c561de5c3ff625c175fcd! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3782-pull_request-663

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 991d4507fa2bcf36cd2164fb3ce916334dbc41b7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3784-pull_request-663

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e938721a00e5c82c5462b84d067e3d3d8515ce77! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3786-pull_request-663

**Review by yagee-de — APPROVED** [review]

**Pull request merged**
