### PR TITLE
MCR-1739 Upgrade to Java 11

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-1739).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8f4993ba4fa908e4f0e4a40d4d64336a85fbed5d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4179-pull_request-745

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 86f05f72491417887b9716c837f9a26226e48665! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4181-pull_request-745

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8cb6c66fc628e16e100075ddfc8f4c6dee3d9ceb! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4183-pull_request-745

**Review by sebhofmann — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on cc3680b115c2a5f998267cd262fced478b812f9f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4185-pull_request-745

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on ce04b74b699a5f0c1dfd598b5655b1c18b4180da! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4191-pull_request-745

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 9ae869577df85a67b01a76bd58d5fe3be222956e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4195-pull_request-745

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 9ae869577df85a67b01a76bd58d5fe3be222956e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4195-pull_request-745

**Review by eckstueck — APPROVED** [review]

**Pull request merged**
