### PR TITLE
MCR-2011 fix mimeType based encoding

### PR DESCRIPTION
**Pull request by adlerre**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2011).

### CODE REVIEW

**Comment by kkrebs** [comment]
shouldn't this be also fixed in LTS2018? Or is this bug master specific?

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 0c2a5744e9073bd93ca9875c4394ddf26e565f51! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4245-pull_request-755

**Review by fluetze — APPROVED** [review]
Looks impressive, but personally, I'm not sure it fixes my issue. But ok.

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 0c2a5744e9073bd93ca9875c4394ddf26e565f51! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4245-pull_request-755

**Pull request merged**
