### PR TITLE
MCR-2341 fixed xsl:iterate in translate-with-params

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2341).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 615b1252a736aba4ff0026fb859fc4a72bf8180e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6458-pull_request-1161

**Review by rsteph-de — APPROVED** [review]
tested locally and the warning is gone

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 615b1252a736aba4ff0026fb859fc4a72bf8180e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6458-pull_request-1161

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 615b1252a736aba4ff0026fb859fc4a72bf8180e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6458-pull_request-1161

**Pull request merged**
