### PR TITLE
MCR-2378 (4) remove guice configuration

### PR DESCRIPTION
**Pull request by rsteph-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2378).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 645b2bfc0303d3cb34da108da7d8e50aac35e1c7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6893-pull_request-1220

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 645b2bfc0303d3cb34da108da7d8e50aac35e1c7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6893-pull_request-1220

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 645b2bfc0303d3cb34da108da7d8e50aac35e1c7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6893-pull_request-1220

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b077002ea75feb1548e3e55d84d6b45a77634f94! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6897-pull_request-1220

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on d46d73c3e66745ec0737b3f7af2bf8e2bafc095d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6901-pull_request-1220

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
