### PR TITLE
MCR-2753 fix NPE with flags in ObjectService

### PR DESCRIPTION
**Pull request by rsteph-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2753).

### CODE REVIEW

**Review by bt1cu — APPROVED** [review]

**Review by sebhofmann — DISMISSED** [review]
The NPE is actually correct. By changing the equals you only cover up the real error, which is missing validation of the object.

**Comment by sebhofmann** [comment]
A better place to fix that would be in the setFromDOM or in the validate method.

**Comment by rsteph-de** [comment]
That depends ...
The given example was
```
   <servflags class="MCRMetaLangText"> 
     <servflag inherited="0" form="plain">State:original sample</servflag> 
   </servflags>
```

And because the `@type`-Attribute is optional in MCRMetaLangText I would not handle things different for servflags.
Which means that we must rework the API to allow `type=null` where it occurs.

**Comment by rsteph-de** [comment]
> The NPE is actually correct. By changing the equals you only cover up the real error, which is missing validation of the object.

type attribute is optional - see XML Schema for MCRMetaLangText

**Pull request merged**
