### PR TITLE
MCR-2375 reduce icu dependencies

### PR DESCRIPTION
**Pull request by rsteph-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2375).
This pull request reduces usage of ICU API to MCRCalendar and MCRMetaHistoryDate.
With another / new pull request I am going to move the ICU API usage / dependency into a new mycore-module

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on ef182407f48ef37221957b3b44ab13055125a8d6! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6765-pull_request-1202

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4421fd66746e86a19f37d9b41c991083bf83147c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6767-pull_request-1202

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4421fd66746e86a19f37d9b41c991083bf83147c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6767-pull_request-1202

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8261cff0a244c51b392f373041c49df82a4e11f9! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6769-pull_request-1202

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
