### PR TITLE
MCR-2264 add 'set classification of derivate {0} to {1}' command

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2264).

### CODE REVIEW

**Comment by sebhofmann** [comment]
maybe it would be better if you could pass a comma seperated list of classifications.

**Comment by yagee-de** [comment]
> maybe it would be better if you could pass a comma seperated list of classifications.

Do we have a use-case with a derivate having more than one classification category?

**Comment by rsteph-de** [comment]
> Do we have a use-case with a derivate having more than one classification category?

Currently I haven't, but since we are using "standard MyCoRe classification behaviour" internally, we should be prepared for that.

**Comment by yagee-de** [comment]
> > Do we have a use-case with a derivate having more than one classification category?
> 
> Currently I haven't, but since we are using "standard MyCoRe classification behaviour" internally, we should be prepared for that.

OK, solr field definition is also multivalued already. Implemented requested changes.

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 518354a9b798617bd860a9c4f626ba841a7555cf! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5892-pull_request-1044

**Comment by sebhofmann** [comment]
Its only possible to set derivate_types not all other classifications.

**Comment by rsteph-de** [comment]
and advanced command call could look like this:
`set classification of derivate mir_derivate_0123 to derivate_types:fulltext,derivate_types:cover,hello:world`

**Comment by yagee-de** [comment]
> and advanced command call could look like this:
> `set classification of derivate mir_derivate_0123 to derivate_types:fulltext,derivate_types:cover,hello:world`

or simplier
* single default classification: `set classification of derivate mir_derivate_12345678 to content`
* multiple combined: `set classification of derivate mir_derivate_12345678 to content,hello:world`

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
