### PR TITLE
MCR-2332 commands to load update classification from uri

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2332).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on d31d0ce0be5b3746e1474f74970b174952bd063d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6350-pull_request-1136

**Review by fluetze — CHANGES_REQUESTED** [review]
Why not use MCRSourceContent.getInstance( String uri ).asXML();
Why not completely replace  existing "from url" method?

**Comment by sebhofmann** [comment]
> Why not use MCRSourceContent.getInstance( String uri ).asXML();

I will change that.

> Why not completely replace existing "from url" method?

Because i want this change in LTS and its would be a to big semantically change in my opinion.

**Comment by rsteph-de** [comment]
Nice Feature, it allows us finally to load classifications from classpath.

I would suggest to delete the "from url" commands only in master (to keep list of commands clean).

**Review by fluetze — APPROVED** [review]

**Pull request merged**
