### PR TITLE
MCR-2261 change css compressor to google closure

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2261).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c47f0abcead911a38a5d2e3c0853f9d03d15d25b! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5905-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19d96eaca735678baf5cfcbb37d13c71f04a4ba2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5906-pull_request-1047

**Review by yagee-de — CHANGES_REQUESTED** [review]
Keeping attribution comments is important. They may not be removed!

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e27877f92ac3ae7fd24311858282551c9c5a2362! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5921-pull_request-1047

**Comment by sebhofmann** [comment]
The following comments are preserved:
* `@preserve`
* `@license`
* `/*! (start of comment)`

**Review by kkrebs — APPROVED** [review]

**Comment by kkrebs** [comment]
looks good, layout bugs are fixed now
🚢

**Review by yagee-de — APPROVED** [review]

**Pull request merged**
