### PR TITLE
MCR-2203 added getter and setter for EnrichedLinkID

### PR DESCRIPTION
**Pull request by sebhofmann**
WARNING: did not test the derivate restapi code
[Link to jira](https://mycore.atlassian.net/browse/MCR-2203).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 19e72debaeacf5a849d7992b96aa0ff556c5b2f2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5522-pull_request-965

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-restapi/src/main/java/org/mycore/restapi/converter/MCRMetaDefaultListJSONWriter.java  1
- mycore-base/src/test/java/org/mycore/datamodel/metadata/MCRMetaEnrichedLinkIDTest.java  1
- mycore-base/src/main/java/org/mycore/datamodel/metadata/MCREditableMetaEnrichedLinkID.java  1
         

Complexity decreasing per file
==============================
+ mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIUploadHelper.java  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5511808&bid=18063333)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 47aa070e63c3435d184b2b0068cf24de578adb03! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5530-pull_request-965

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-restapi/src/main/java/org/mycore/restapi/converter/MCRMetaDefaultListJSONWriter.java  1
- mycore-base/src/test/java/org/mycore/datamodel/metadata/MCRMetaEnrichedLinkIDTest.java  1
- mycore-base/src/main/java/org/mycore/datamodel/metadata/MCREditableMetaEnrichedLinkID.java  1
         

Complexity decreasing per file
==============================
+ mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIUploadHelper.java  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5511808&bid=18063333)

**Pull request merged**
