### PR TITLE
MCR-1907 add runtime compatiblity for Java 10

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-1907).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 07243f81c7f60d04f27bf94cca2272f710a7e617! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3708-pull_request-648

**Review by Mewel — COMMENTED** [review]
Can't test in jportal cause it runs on 2018.06.0.1-SNAPSHOT and not 2018.08-SNAPSHOT

**Review by Possommi — APPROVED** [review]
Seems to work.

**Comment by bt1cu** [comment]
Test with Java JRE 10 : no problem found

**Review by bt1cu — APPROVED** [review]
it works

**Pull request merged**
