### PR TITLE
MCR-2100 deprecate MCRHIBConnection.getSession()

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2100).

### CODE REVIEW

**Comment by yagee-de** [comment]
Pay attention: Rather big change but pretty straight forward.
deprecates the method to retrieve Hibernate session and pushes users to JPA

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 2c1347acd1744b483024e28619b52029781fd6a7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6435-pull_request-1154

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c0e0da2c0d96fb60d32f715735fe14888c39a14d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6437-pull_request-1154

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on d47277152da670830683658bbb968682496a8270! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6439-pull_request-1154

**Review by Possommi — APPROVED** [review]

**Comment by sebhofmann** [comment]
Need a MIR branch to test that.
Edit: Maybe we should move that deprecated to master, because this requires "API changes".

**Review by kkrebs — CHANGES_REQUESTED** [review]
see sebastians comment!

**Comment by yagee-de** [comment]
Those deprecated methods are not an API change. They show that methods or classes are removed in a later release. You can prepare your code early while paying attention to those changes. EntityManager support is already available in LTS 2020!

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
