### PR TITLE
MCR-3005 remove test scope for com.zaxxer:HikariCP in mycore-bom

### PR DESCRIPTION
**Pull request by rsteph-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-3005).

### CODE REVIEW

**Review by yagee-de — CHANGES_REQUESTED** [review]
I think the test scope is OK. HikariCP is not required and can be used like H2 in your app, just set the scope to "compile" there.

**Comment by rsteph-de** [comment]
> I think the test scope is OK. ... just set the scope to "compile" there.

Just tried it - does not work for me.
I added the dependency in the myapp-common Maven-module (with scope=compile) to be available in myapp-webapp and myapp-cli. But somehow it is not copied into the webapp's  WAR file or the cli's lib directory.

**Comment by rsteph-de** [comment]
> HikariCP is not required and can be used like H2 in your app

Since C3P0 is not working with the Jakarta configuration, HikariCP is the new connection pooling for all of us. The definition via `dependencyManagement does not say whether the library is finally used or not.

**Review by kkrebs — APPROVED** [review]
We had the same problem with mycore-classification, see https://mycore.atlassian.net/browse/MCR-2905

only removing test scope helps here

**Comment by yagee-de** [comment]
OK

**Review by yagee-de — APPROVED** [review]

**Pull request merged**
