### PR TITLE
MCR-2315 (Fix inverted Base-ID check in MCRCommandUtils)

### PR DESCRIPTION
**Pull request by OPNA2608**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2315).

Bug introduced in #1117.

### CODE REVIEW

**Review by bt1cu — APPROVED** [review]
okay

**Comment by yagee-de** [comment]
Should be MCR-2315 and not a new ticket, as MCR-2315 is not yet released. Please change commit message (branch name is not of that importance).

**Comment by OPNA2608** [comment]
Like this?

**Review by yagee-de — APPROVED** [review]
Yep like this ;-)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 12444d227a745edb6c65c86823fc2423c5009a1e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6374-pull_request-1140

**Pull request merged**
