### PR TITLE
MCR-2390 some metadata is missing in csl citation styles

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2390).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 7af8b533bf92dd8cd256d84a394f89d87f905494! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7019-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on bd2ab1df18b5fcebec3b815218e55f95769d1271! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7024-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on f2a922433b71c0ef95c2ee1e19c9557485224fec! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7026-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 1752cae50926392c96a9be53b7919fc818c5beb8! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7028-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a8dd159a0393c84535138deff892013b40afc767! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7030-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e591addc1ee0bbf76aae47470d392a3a8460a8e5! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7032-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 778a98dc87d65e65b0797df177169ce1dee520b3! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7034-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 3a4ed04dc40c92210d7ce03cae7ce2db0090323d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7036-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e29535a5bc2cbe32a5ff630bd07aa8645c4372ad! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7040-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 145e2aaa2e78c79397a7d584f0f3480ce6baf653! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7044-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on df4b05af63b335cb7af4ab673a0d84cbc157700e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7048-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on f8eccec17626efd5bc93bbb4bfc7e2300e5e37d8! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7052-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 55d7a9adbf0e72d530badcad6c0b04c07a7db9c6! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7054-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8d7a34bfb2deeeb9766c9453abf829f0846062c1! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7056-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b50b7ec5179517d27d38e7af0e39d17c7fe2f1e4! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7058-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 6843a0ca2dbe3fea016a70b41f6b6bfe2647c445! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7061-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 0f4091ec2b2e60cb0ab89d5158558010f12448a6! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7063-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b978aa7fd97631b585ce0d7d31bdda5c60d26f6f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7065-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 592c9bae2fc9bcf23abd52389c005f5108d492b3! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7067-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on f39f376af4beb6bffc180d577575c69f0a2897d4! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7071-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 023b3c4e31d7507dd86c69903b16fc7ecdf7a589! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7073-pull_request-1231

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b531aeae7f9e4754cfcb33a28e19bf9765bb5f1d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7077-pull_request-1231

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
