### PR TITLE
MCR-2779 empty nameIdentifier results in exception

### PR DESCRIPTION
**Pull request by eckstueck**
- skip empty nameIdentifier

[Link to jira](https://mycore.atlassian.net/browse/MCR-2779).

### CODE REVIEW

**Comment by golsch** [comment]
Perhaps a log message would still be useful if the problem occurs. Or are there identifiers which are inserted without type attribute?

**Review by fluetze — CHANGES_REQUESTED** [review]
This is jsut a workaround for inconsistent stored data that actually obfucates the root cause. There never should be a stored publication with empty name identifiers!

**Review by kkrebs — APPROVED** [review]

**Comment by eckstueck** [comment]
For my understanding the MODS Schema allows empty nameIdentifier. So it is possible that you run in to this problem.

**Comment by fluetze** [comment]
So, what does that mean if our data contains such an empty name identifier? How do we use and visualize that.
From my point of view, an empty name identifier is just a bug in the data. I'd then assume that some cleanup or import process failed - and we should fix THAT process, not the ORCID code - which should rely on meaningful data.

**Review by kkrebs — APPROVED** [review]

**Review by kkrebs — CHANGES_REQUESTED** [review]
please only allow empty type and fix codacy error

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
