### PR TITLE
MCR-2062 Epub support for mycore-viewer

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2062).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on edf4e0c757dfe48024ec4edb96d37cebe5b92e2c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4588-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 29513e12a72dc8d1d6945923fa51180710fe743e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4590-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e3ae0660ceb0227af836077c5a0dace4fcf5fc84! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4592-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 1150d654b8cea3645a5e769113fc95e8fbe057d7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4594-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a5485c31674445f23dd9ab4e6c45d6f7d272946c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4596-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on ec3fdd2addf03256be003e8969eb69f494c17e1e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4598-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 2a238f2caf148e431dee8cfb303ce271a95f579e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4600-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on edbe73fce6199a81013ba7da759e08be69455b8d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4602-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 3b783f6f3cb4587aa25509ed9845a5a9a612208b! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4604-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c4c48cfb5625546f0eb0fcb6400259e7672f10f1! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4607-pull_request-809

**Review by kkrebs — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 41a44e0d1ac18e1a188a31b6b7c5ff1f566c15f3! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4609-pull_request-809

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8000c76fb71ada6ab0fea88e0ec6c32abece9b5a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4612-pull_request-809

**Pull request merged**
