### PR TITLE
MCR-2745 Allow specific classification values to be exluded from classification browser

### PR DESCRIPTION
**Pull request by toKrause**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2745).

### CODE REVIEW

**Comment by rsteph-de** [comment]
Why is the parameter called `excludeGroups` ? For me this looks like a "normal" list of category IDs.
Never heart about **Groups** in the context of MyCoRe classifications.
I would go for `` excludeCategories or `excludeCategids`

**Comment by toKrause** [comment]
The naming scheme for the existing parameters is a bit of a mess; no clear strategy discernible. So I've gone for the more readable of your two suggestions: `excludeCategories`.

**Review by rsteph-de — DISMISSED** [review]
looks good for me now

**Comment by kkrebs** [comment]
can you rebase this to 2022.06.x please

**Comment by toKrause** [comment]
> can you rebase this to 2022.06.x please

done

**Review by rsteph-de — APPROVED** [review]
looks good for me

**Pull request merged**
