### PR TITLE
MCR-2347 xslt3 migration for solr input

### PR DESCRIPTION
**Pull request by kkrebs**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2347).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4c24885823aab5a5a45a74926de70d7223a72379! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6756-pull_request-1183

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4c24885823aab5a5a45a74926de70d7223a72379! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6756-pull_request-1183

**Comment by rsteph-de** [comment]
use this gist to see difference in` mycoreobject-dynamicfields.xsl`: 
https://gist.github.com/rsteph-de/bb4e882bdd73c6a1a72b31a3ddc9fb71/revisions

**Comment by rsteph-de** [comment]
Was ist der Unterschied zwischen den Basis-Stylesheets für SOLR?
https://github.com/MyCoRe-Org/mir/blob/2020.06.x/mir-module/src/main/resources/xsl/mir-solrbase.xsl
und
https://github.com/MyCoRe-Org/mycore/blob/2020.06.x/mycore-solr/src/main/resources/xsl/mycoreobject-solrdocument.xsl

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
