### PR TITLE
MCR-1937 fixed for metadata api

### PR DESCRIPTION
**Pull request by bt1cu**
[Link to jira](https://mycore.atlassian.net/browse/MCR-1937).

### CODE REVIEW

**Review by sebhofmann — CHANGES_REQUESTED** [review]
The MCRMetaInterface and all Implementations are violating the java clone convetions. We should fix this.

1. All clone methods should throw a CloneNotSupportedExcetion
2. If you implement a clone method, then you always should call super.clone() and the extend the inherited object

Why we have a clone method in MCRMetaInterface which has a different signatur then the original clone method in object?

**Comment by bt1cu** [comment]
MCRMetaInterfache throw now the CloneNotSupportedExcetion as default of clone().

The super.clone() is not required cause we use the XML-create-parse way to get a complete clone. These methods have a super() implicit. This seems the best way to get a correct clone of all data by the same way.

**Comment by sebhofmann** [comment]
JavaDoc of Object.clone says: By convention, the returned object should be obtained by calling super.clone.

**Comment by sebhofmann** [comment]
Creating clones by the XML-create-parse way does not obey Java Convention and has also a big Overhead.

**Review by sebhofmann — APPROVED** [review]

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
