### PR TITLE
MCR-2077 framed epub viewer now loads

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2077).

### CODE REVIEW

**Review by kkrebs — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 68a9e6d4076ac72ee495a10bc0dd02ee9ea53256! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4712-pull_request-828

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 68a9e6d4076ac72ee495a10bc0dd02ee9ea53256! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4712-pull_request-828

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 68a9e6d4076ac72ee495a10bc0dd02ee9ea53256! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4712-pull_request-828

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 68a9e6d4076ac72ee495a10bc0dd02ee9ea53256! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4712-pull_request-828

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c87611c6f588226f14a0eebf9721ef6e757559ac! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4739-pull_request-828

**Pull request merged**
