### PR TITLE
MCR-2012 add xpath to generic pi generator

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2012).

### CODE REVIEW

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-pi/src/main/java/org/mycore/pi/MCRGenericPIGenerator.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425614&bid=17793514)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on ea7a460cc41bb9ca9d51e348e18ed6fa88a84da9! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5458-pull_request-956

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-pi/src/main/java/org/mycore/pi/MCRGenericPIGenerator.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425614&bid=17793514)

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-pi/src/main/java/org/mycore/pi/MCRGenericPIGenerator.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425614&bid=17793514)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 088f55f1615e123dec9bc37714ae5a9493f7fe53! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5495-pull_request-956

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 088f55f1615e123dec9bc37714ae5a9493f7fe53! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5495-pull_request-956

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-pi/src/main/java/org/mycore/pi/MCRGenericPIGenerator.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425614&bid=17793514)

**Review by rsteph-de — APPROVED** [review]
looks good for me

**Pull request merged**
