### PR TITLE
MCR-3068 Deleting directories causes error in MIR

### PR DESCRIPTION
**Pull request by toKrause**
[Link to jira](https://mycore.atlassian.net/browse/MCR-3068).

### CODE REVIEW

**Review by rsteph-de — APPROVED** [review]
looks good for me

**Review by kkrebs — CHANGES_REQUESTED** [review]
please unify slashes handling as discussed in our call yesterday
```
{...
   "type":"directory",
   "name":"test-folder",
   "path":"/test-folder/test-folder/",
   "urlPath":"test-folder/test-folder", ...}
```

**Comment by toKrause** [comment]
For a derivate with the files

```
.
├── bar[]
├── foo
└── outer
    ├── bar[]
    ├── foo
    └── inner[]
        ├── bar[]
        └── foo
```

the generated JSON now looks like this:

```json
{
  "type": "directory",
  "mycoreobject": "macau_mods_00016222",
  "mycorederivate": "macau_derivate_00016222",
  "name": "",
  "path": "/",
  "urlPath": "/",
  ...,
  "children": [
    {
      "type": "directory",
      "name": "outer",
      "path": "/outer/",
      "urlPath": "/outer/",
      "parentPath": "/",
      ...,
      "children": [
        {
          "type": "directory",
          "name": "inner[]",
          "path": "/outer/inner[]/",
          "urlPath": "/outer/inner%5B%5D/",
          "parentPath": "/outer/",
          ...,
          "children": [
            {
              "type": "file",
              "name": "foo",
              "path": "/outer/inner[]/foo",
              "urlPath": "/outer/inner%5B%5D/foo",
              "parentPath": "/outer/inner[]/",
              ...,
              "href": "http://localhost:8080/servlets/MCRFileNodeServlet/macau_derivate_00016222/outer/inner%5B%5D/foo"
            },
            {
              "type": "file",
              "name": "bar[]",
              "path": "/outer/inner[]/bar[]",
              "urlPath": "/outer/inner%5B%5D/bar%5B%5D",
              "parentPath": "/outer/inner[]/",
              ...,
              "href": "http://localhost:8080/servlets/MCRFileNodeServlet/macau_derivate_00016222/outer/inner%5B%5D/bar%5B%5D"
            }
          ]
        },
        {
          "type": "file",
          "name": "foo",
          "path": "/outer/foo",
          "urlPath": "/outer/foo",
          "parentPath": "/outer/",
          ...,
          "href": "http://localhost:8080/servlets/MCRFileNodeServlet/macau_derivate_00016222/outer/foo"
        },
        {
          "type": "file",
          "name": "bar[]",
          "path": "/outer/bar[]",
          "urlPath": "/outer/bar%5B%5D",
          "parentPath": "/outer/",
          ...,
          "href": "http://localhost:8080/servlets/MCRFileNodeServlet/macau_derivate_00016222/outer/bar%5B%5D"
        }
      ]
    },
    {
      "type": "file",
      "name": "foo",
      "path": "/foo",
      "urlPath": "/foo",
      "parentPath": "/",
      ...,
      "href": "http://localhost:8080/servlets/MCRFileNodeServlet/macau_derivate_00016222/foo"
    },
    {
      "type": "file",
      "name": "bar[]",
      "path": "/bar[]",
      "urlPath": "/bar%5B%5D",
      "parentPath": "/",
      ...,
      "href": "http://localhost:8080/servlets/MCRFileNodeServlet/macau_derivate_00016222/bar%5B%5D"
    }
  ]
}
```

**Comment by toKrause** [comment]
Should we add `parentUrlPath` as well, for consistency?

**Comment by rsteph-de** [comment]
> Should we add `parentUrlPath` as well, for consistency?

In my opinion this is not necessary, because the information can be retrieved from parent structure

**Comment by rsteph-de** [comment]
looks good for me now.

**Review by rsteph-de — APPROVED** [review]

**Pull request merged**
