### PR TITLE
MCR-2082 improve mods crossref xsl

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2082).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on bad9382ff2aca366285ce5629cc5415d63b738d2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4750-pull_request-834

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on bad9382ff2aca366285ce5629cc5415d63b738d2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4750-pull_request-834

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on bad9382ff2aca366285ce5629cc5415d63b738d2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4750-pull_request-834

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on bad9382ff2aca366285ce5629cc5415d63b738d2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4750-pull_request-834

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c9925981e21e163d89d095ad9ddee4139e802b35! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4876-pull_request-834

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
