### PR TITLE
MCR-2035 MCRURIResolver can deadlock

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2035).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a85f9c08c0bb8c2dc07c72e3b0f3ebb0c2b4c844! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4641-pull_request-818

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a85f9c08c0bb8c2dc07c72e3b0f3ebb0c2b4c844! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4641-pull_request-818

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a85f9c08c0bb8c2dc07c72e3b0f3ebb0c2b4c844! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4641-pull_request-818

**Review by fluetze — CHANGES_REQUESTED** [review]
You could just use 
new MCRStreamContent(inputStream).getReusableCopy().getSource()
i think

**Review by fluetze — APPROVED** [review]

**Pull request merged**
