### PR TITLE
MCR-2243 add xsl:function to convert mods to mycoreclass

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2243).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a48001b970335ce6d621e6a09ff0e08a06b4b3ac! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5747-pull_request-1016

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on cbb9bdcf319280dd707d715015bd6bf57449fdea! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5749-pull_request-1016

**Review by fluetze — COMMENTED** [review]
Wouldn't it be better to choose another separator, not slash?
mycoremods:/{sourcePath}/{subPath}
for example, with authorityURI and valueURI as parameters, both separated by a "/" ?

**Comment by yagee-de** [comment]
> Wouldn't it be better to choose another separator, not slash?
> mycoremods:/{sourcePath}/{subPath}
> for example, with authorityURI and valueURI as parameters, both separated by a "/" ?

I think that '/' as a seperator shows the hierarchical nature better: ´, e.g.`modsclass:/authority/marcrelator/aut`
Another issue with 'query parameters' would be the usage of an URLEncoder that is, as far as I know, not available in XSL (yet) to encode the values. In the current state I could simply use the build-in `fn:encode-for-uri()`.

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
