### PR TITLE
MCR-1839 mycore-mets and tei refactoring

### PR DESCRIPTION
**Pull request by sebhofmann**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 381410cbe2f5d7d13ace1595cacb6a435d678465! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3040-pull_request-552

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 57560a9853c87b91cc7cd69de9ab27f9f4940f0b! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3044-pull_request-552

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 31bc201caa3a1855e293782e5b89fb709efc2be1! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3046-pull_request-552

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 70c26fe7fa969f0d462875fc321b693fbbdb93f6! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3050-pull_request-552

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 645e86babc44e1b99c78a2900595fb498753ba8f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3052-pull_request-552

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 9454c832ce420460816acd2919c87c5f6acab052! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3054-pull_request-552

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 6b0fe023d018d7ce6cad07da69e310ebfd200a40! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3118-pull_request-552

**Review by Mewel — APPROVED** [review]
Works in JPortal

**Pull request merged**
