### PR TITLE
Issues/mcr 1883 add orcid functionality to interact with users

### PR DESCRIPTION
**Pull request by fluetze**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8a2541f14f2a2d3b9f8702e122c070f4730796aa! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3427-pull_request-607

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b87f308ef23fdcde3e32d6e1fdced499984be458! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3429-pull_request-607

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8ab7fd358fcabd9c2792c03bff5f41c3131a060f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3435-pull_request-607

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 7d9bed0b1e8d7cd142cf5a7497c1bca545962992! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3437-pull_request-607

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
