### PR TITLE
MCR-2194 Decouple Solr response header

### PR DESCRIPTION
**Pull request by bt1cu**
A property list can be used to replace / delete  SOLR response header
attributes (see javadoc)

[Link to jira](https://mycore.atlassian.net/browse/MCR-).

### CODE REVIEW

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-solr/src/main/java/org/mycore/solr/proxy/MCRSolrProxyServlet.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5524365&bid=18101511)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on dbe526320556016462c2ef31cf8e87287a2ad7e0! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5534-pull_request-967

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-solr/src/main/java/org/mycore/solr/proxy/MCRSolrProxyServlet.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5524365&bid=18101511)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a561870a3a792bfb2b71a64bda81818256b646bc! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5538-pull_request-967

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-solr/src/main/java/org/mycore/solr/proxy/MCRSolrProxyServlet.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5524365&bid=18101511)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on cd25ff4ce677320e664d474c3b8c931ffb4b512b! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5540-pull_request-967

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-solr/src/main/java/org/mycore/solr/proxy/MCRSolrProxyServlet.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5524365&bid=18101511)

**Review by yagee-de — APPROVED** [review]

**Pull request merged**
