### PR TITLE
MCR-2793 Make password pattern configurable

### PR DESCRIPTION
**Pull request by toKrause**
**Relies on [MCR-2792](https://mycore.atlassian.net/browse/MCR-2792).**

[Link to jira](https://mycore.atlassian.net/browse/MCR-2793).

[MCR-2792]: https://mycore.atlassian.net/browse/MCR-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by yagee-de** [comment]
"matches-not" is not used anywhere. This PR could be simplified. Please open a new ticket and PR, if "matches-not" is required elsewhere.

**Comment by toKrause** [comment]
> "matches-not" is not used anywhere. This PR could be simplified. Please open a new ticket and PR, if "matches-not" is required elsewhere.

The validator „matches-not“ is not part of this PR. It is part of the more generic MCR-2792, which this PR relies upon. This PR is still stacked and will be rebased once MCR-2792 has been merged.

**Comment by toKrause** [comment]
> The validator „matches-not“ is not part of this PR. It is part of the more generic MCR-2792, which this PR relies upon. This PR is still stacked and will be rebased once MCR-2792 has been merged.

Correction: _was_ part of MCR-2792. Iv split that PR into MCR-2792 and MCR-2807 to give each feature it's own PR and reduce confusion (in the long term).

**Review by kkrebs — APPROVED** [review]

**Comment by kkrebs** [comment]
[MCR-2792](https://mycore.atlassian.net/browse/MCR-2792) is merged now. Is a rebase needed?

[MCR-2792]: https://mycore.atlassian.net/browse/MCR-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by toKrause** [comment]
Is now rebased.

**Pull request merged**
