### PR TITLE
MCR-2550 migrate from j2ee to jakarta

### PR DESCRIPTION
**Pull request by yagee-de**
simplified MCRJerseyTest
updated dependencies

[Link to jira](https://mycore.atlassian.net/browse/MCR-2550).

### CODE REVIEW

**Comment by yagee-de** [comment]
requires merge of https://github.com/MyCoRe-Org/easy-sword2-lib/pull/4 and https://github.com/MyCoRe-Org/image-tiler/pull/22

**Review by fluetze — DISMISSED** [review]

**Comment by kkrebs** [comment]
will be merged after release, thats why I convert this to draft again

**Review by sebhofmann — DISMISSED** [review]

**Comment by sebhofmann** [comment]
The Image-Tiler jakarta branch is required

**Comment by yagee-de** [comment]
> The Image-Tiler jakarta branch is required

merged https://github.com/MyCoRe-Org/image-tiler/pull/22

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
