### PR TITLE
MCR-2081 epub viewer sometimes jumps to wrong chapter

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2081).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e29144ccb3b9f846169e489a990daff6ab9c02dd! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4744-pull_request-833

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e29144ccb3b9f846169e489a990daff6ab9c02dd! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4744-pull_request-833

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e29144ccb3b9f846169e489a990daff6ab9c02dd! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4744-pull_request-833

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e29144ccb3b9f846169e489a990daff6ab9c02dd! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4744-pull_request-833

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a1141307ca659ac484fb3087be41733f4a5c103c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4746-pull_request-833

**Review by kkrebs — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a1141307ca659ac484fb3087be41733f4a5c103c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4746-pull_request-833

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a1141307ca659ac484fb3087be41733f4a5c103c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4746-pull_request-833

**Pull request merged**
