### PR TITLE
MCR-1580 move sass compiler from MIR to MyCoRe

### PR DESCRIPTION
**Pull request by sebhofmann**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on aa56841117efd16d61d1c71db3b44d051f10e033! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1258-pull_request-224

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8ba9bc8dc9e443d18a6aa09f3077be023e0ecacc! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1260-pull_request-224

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 430f8aae6a15998fb5f6568538235131afe2a194! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1262-pull_request-224

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 71743f2216c9a79c75714f49b3ff22b637243044! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1264-pull_request-224

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 71743f2216c9a79c75714f49b3ff22b637243044! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1264-pull_request-224

**Review by yagee-de — APPROVED** [review]

**Pull request merged**
