### PR TITLE
MCR-1490 make mets editor frontend a MyCoRe module

### PR DESCRIPTION
**Pull request by sebhofmann**

### CODE REVIEW

**Comment by sebhofmann** [comment]
Do not merge yet. just testing..

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 03ce4ff12a0fd5c1141ee3c1b4b02131dbfb1a49! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/990-pull_request-123

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 3e16740e70f0726b2a687bbcb533cea18e5436ae! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/992-pull_request-123

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 35074a1f6c8d4e14d30c76bc5052ea186d4dc9e8! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1000-pull_request-123

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 9139d7decfb22de7d3e27871778c9ee07b978be2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1006-pull_request-123

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 59428abbeb07fb11b90d8040c4396a3c35a1471f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1008-pull_request-123

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 60c1334d163b7787da9f65174c6b0d4c054a6c8b! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1068-pull_request-123

**Pull request merged**
