### PR TITLE
MCR-2647 hibernate 6 jpa 3.1

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2647).

### CODE REVIEW

**Comment by yagee-de** [comment]
Waits currently for fix of https://hibernate.atlassian.net/browse/HHH-15331

**Comment by yagee-de** [comment]
Ready for review!
Includes latest hibernate and H2 version
Tested with https://github.com/MyCoRe-Org/mir/pull/907

**Comment by rsteph-de** [comment]
We have already MyCoRe applications, that are based the main branch / LTS 2023.06 and in production. 
This change needs a migration guide and the merge should be announced on the developer's list.

As far as I can see, at least the persistence.xml changes. Anything else?

**Comment by yagee-de** [comment]
> We have already MyCoRe applications, that are based the main branch / LTS 2023.06 and in production. This change needs a migration guide and the merge should be announced on the developer's list.
> 
> As far as I can see, at least the persistence.xml changes. Anything else?

Tested with postgres in mir-docker and this requires no migration, also those old properties (javax.* instead of jakarta.*) seems to work (but produce a warning).

For development environments this requires to migrate to a newer version of H2.

1. Use web console with your old version of h2
`java -jar h2-1.4.199.jar` and connect to your database (same URI as in persistence.xml)
export database to SQL file
`SCRIPT TO '/path/to/backup-1.4.sql'`
stop old H2 instance
2. Move or delete H2-Database directory
3. [Create new database](http://www.h2database.com/html/tutorial.html#creating_new_databases) with version 2.2.x
4. Connect to new database (same steps as in 1. but with newer version of H2)
`RUNSCRIPT FROM '/path/to/backup-1.4.sql' FROM_1X`
`ALTER TABLE MCRUSERATTR ALTER COLUMN "VALUE" RENAME to "value"`

**Comment by yagee-de** [comment]
Also note: If you have custom JQL queries in your code: They are validated more strictly and no "guessing" is done anymore in Hibernate 6.x. But all those obstacles in MyCoRe should be tackled in this PR.

**Pull request merged**
