### PR TITLE
MCR-1726 fix deadlock in MCRShutdownHandler

### PR DESCRIPTION
**Pull request by yagee-de**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e1456b0e68d9d8ab251e72841d23cfc17fa71c43! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2214-pull_request-407

**Review by bt1cu — COMMENTED** [review]
It seems that the bug is fixed.

**Review by bt1cu — COMMENTED** [review]
It seems that that bug is fixed.

**Review by bt1cu — APPROVED** [review]
You can merge it.

**Pull request merged**
