### PR TITLE
MCR-1959 add '/api/v2/events' to broadcast repository events

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-1959).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 87c8aa288b826f04c18a3b76134b506c41b976b7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3995-pull_request-703

**Review by fluetze — COMMENTED** [review]
This is a pull (get) request?
Wouldn't it be better to implement it as a push (post), a webhook to registered receipients?
Like, for example, here: https://developer.github.com/webhooks/

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 811b94941768f1c979c26991979e09b1417a4efc! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3997-pull_request-703

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a3d99d3eef226db5483c7c7711c0927960ae4431! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/3999-pull_request-703

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 3d4d7695a7f92c636e2d9694a79eda85c37a3881! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4001-pull_request-703

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c2543239beb722e271300128839c15120f8f4734! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4003-pull_request-703

**Pull request merged**
