### PR TITLE
MCR-1647 remove Bower, because it is deprecated

### PR DESCRIPTION
**Pull request by eckstueck**
- moved bower dependencies to yarn
- removed bower
- updated yarn to 0.24.6
- updated frontend.maven.plugin to 1.4

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c0619421816146ef93ca093b73f80b4ce96829c9! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1794-pull_request-306

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c0619421816146ef93ca093b73f80b4ce96829c9! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1794-pull_request-306

**Review by kkrebs — CHANGES_REQUESTED** [review]
There are test failures please fix

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 2ce6691b547bac39de799ff2462da3582c87a1f6! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1800-pull_request-306

**Comment by eckstueck** [comment]
test failures are now fixed

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
