### PR TITLE
MCR-2387 improve csl to pdf function

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2387).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on fe9fe8c3839e19bf243e469826037c6b3c32c888! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7008-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 45a136c6c80cc019cc738382334a1175cf960de0! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7010-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 9870ed1f0f4298a62df574209ab8128915c1d09c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7017-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 98a59df3865bc140d42bd5cfab55b2febab33592! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7015-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b1d16e237ec2b58c87c173146368864009630f6f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7022-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4c105f3356e9b0b95dd8645fc663db403ef428eb! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7038-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4c105f3356e9b0b95dd8645fc663db403ef428eb! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7038-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on c06b8265ec91608284cba1d56fb665dfe24f2a23! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7042-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on ebcf5fe0f18cd83d8793b81239046ca9b65c18ef! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7046-pull_request-1230

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on ff11f24f35d15c416239ffa9ecd534bc3e4da8db! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7050-pull_request-1230

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
