### PR TITLE
MCR-604 cleanup MCRCalendar class from redundant code and add support for missing calendars

### PR DESCRIPTION
**Pull request by michael-becker**
This PR cleans the MCRCalendar class from redundant code and adds support for missing calendars. Since the class is heavily rewritten, I added a lot of tests in MCRCalendarTest to show functionality.

The following calendars are supported with this PR
* Gregorian
* Julian
* Islamic
* Hebrew
* Coptic
* Ethiopian
* Japanese 
* Buddhist
* Persian
* Armenian
* Egyptian

Two existing tests were modified due to the following reasons
* MCRXMLFunctionsTest#getISODateFromMCRHistoryDate: 1964 was a leap year so last day in February was the 29th
* MCRMetaHistoryDateTest#checkCreateParseEqualsClone: clearified behaviour

[Link to jira](https://mycore.atlassian.net/browse/MCR-604).

### CODE REVIEW

**Comment by michael-becker** [comment]
I fixed the Codacity issues in the main code, the test code still has issued with long methods.

**Comment by michael-becker** [comment]
@rsteph-de  a remark about ICU JAR size: unfortunately, it is not per se possible to use a smaller JAR. It is only possible to configure ICU resources using the ICU Data Build Tool (https://unicode-org.github.io/icu/userguide/icu_data/buildtool). But that seems a little bit too much effort for reducing the size.

**Review by rsteph-de — DISMISSED** [review]
Looks good for me now

**Comment by michael-becker** [comment]
now resides in https://github.com/MyCoRe-Org/mycore/pull/1616

**Pull request closed without merging**
