### PR TITLE
MCR-2113 delay solr indexing 

### PR DESCRIPTION
**Pull request by rsteph-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2113).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on f06731aac34fd276065d096e859cc38d2167a1fa! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4984-pull_request-867

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e53119c0e848877b9ce6ff0b06c5203d50d66648! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4986-pull_request-867

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8a00921bc57512ba39f8e23a7f2e4579bc755ab8! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4988-pull_request-867

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 8a00921bc57512ba39f8e23a7f2e4579bc755ab8! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4988-pull_request-867

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 3b17cf05186d4034d95d8e4e87e548818893f36c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5000-pull_request-867

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
