### PR TITLE
MCR-2362 add XSL3 postprocessor for editor framework

### PR DESCRIPTION
**Pull request by rsteph-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2362).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 439f4fee8bbd69b1b0636dc3d68c99b0cd58bb83! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6670-pull_request-1191

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 62389cfd970031dda4ac3b00b73fa2324a816ca0! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6672-pull_request-1191

**Review by sebhofmann — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on ed6461523e2963d34cda746a6247aa0afba634b2! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6689-pull_request-1191

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 2058b1171d07707ed401a916f4b21866b80302bd! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6691-pull_request-1191

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 1ce193bb84401cfe5ed4635ec1dbb475eef3b614! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6693-pull_request-1191

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b4155db941d6a7f3e81b14e0737fa765ee3346b3! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6695-pull_request-1191

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 2058b1171d07707ed401a916f4b21866b80302bd! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6691-pull_request-1191

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 1ce193bb84401cfe5ed4635ec1dbb475eef3b614! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6693-pull_request-1191

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on cc271d06f6a6a83c9beb3be830e6557021c8ada1! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6699-pull_request-1191

**Pull request merged**
