### PR TITLE
MCR-1082 make MCRConfiguration* use common helper class

### PR DESCRIPTION
**Pull request by yagee-de**
* MCRConfigurationBase is used for basic handling configuration properties
* MCRConfiguration is refactored to use MCRConfiguration2 as proof-of-work
* fix some bugs of MCR-1783 by the way

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a159ed93f3b81b01dc0353ac8bb45288176bf095! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2747-pull_request-500

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on f28d44264177c89d53928e5874a70574c0dd741f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2774-pull_request-500

**Review by Mewel — APPROVED** [review]
Works with jportal.

**Review by Possommi — COMMENTED** [review]
Works for me.

**Pull request merged**
