### PR TITLE
MCR-1797 Choosing type of url has no effect

### PR DESCRIPTION
**Pull request by eckstueck**
added translation to all url types

### CODE REVIEW

**Comment by eckstueck** [comment]
related to https://github.com/MyCoRe-Org/mir/pull/215

**Review by kkrebs — APPROVED** [review]

**Comment by kkrebs** [comment]
can you please fix codacy issue? thx

**Comment by eckstueck** [comment]
Can't fix codacy issue, second concat is needed.

**Comment by kkrebs** [comment]
What is with:
```
<xsl:value-of select="i18n:translate(concat('component.mods.metaData.dictionary.url.',mcrxsl:regexp(@access,' ','_')))" />
<xsl:text>:</xsl:text>
```
or
```
<xsl:variable name="urlLabel" select="i18n:translate(concat('component.mods.metaData.dictionary.url.',mcrxsl:regexp(@access,' ','_')))" />
<xsl:value-of select="concat($urlLabel, ':')" />
```

**Pull request merged**
