### PR TITLE
MCR-2140 return element always with position bracket to make it unique

### PR DESCRIPTION
**Pull request by kkrebs**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2140).

This is only the fix. Maybe some tests and implementations need adoptions now ... we have to check this before merging!

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 313c2eb7b9895e09ce228f3e3d975b3a90460f9a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6274-pull_request-1120

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 491b2654016ae1e6cba056e97d22942e87786510! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6276-pull_request-1120

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b8631ba5c09c487984ae2efb3d091a3a31e5d584! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6316-pull_request-1120

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on b8631ba5c09c487984ae2efb3d091a3a31e5d584! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6316-pull_request-1120

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 891a637ad1003cfb4b0e7e046e5f1d3de247ac13! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6377-pull_request-1120

**Review by fluetze — APPROVED** [review]

**Comment by kkrebs** [comment]
# Do not delete this branch!
... it`s in use atm

**Pull request merged**
