### PR TITLE
MCR-2110 cleanup code

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2110).

Ready for review!

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 6c6747fbb02ce61275df65fadd739fefc8ac4c4c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5011-pull_request-871

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a2ad57f8e182586e6f0d3bbf836c005840c82064! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5025-pull_request-871

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a2ad57f8e182586e6f0d3bbf836c005840c82064! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5025-pull_request-871

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a2ad57f8e182586e6f0d3bbf836c005840c82064! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5025-pull_request-871

**Review by kkrebs — APPROVED** [review]
successfully tested with mycore application CMO (skeleton based)

**Review by rsteph-de — APPROVED** [review]
works for me

**Pull request merged**
