### PR TITLE
MCR-1685 #comment integrate ACL-checks in REST-API

### PR DESCRIPTION
**Pull request by rsteph-de**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 1a78b88063aa5fb15af1f028a8c3ef96e26a3402! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1989-pull_request-358

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a825ef122b9f342195b6d0dc35fa99ae7f574efe! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1991-pull_request-358

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on f6276c707c7f49fc539c56ca9dc25a02fdeb6c29! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1995-pull_request-358

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 22fc2547e823de446b71ecf37b616b2459ab6ce7! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1998-pull_request-358

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
