### PR TITLE
MCR-2192 mycore-csl

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2192).

### CODE REVIEW

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5400523&bid=17704503)

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5400523&bid=17704503)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 83f14c745c5945eca17ef1333338e793ee40f8b3! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5428-pull_request-952

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 9384839c354b498bb493f64e62d110ad0599e37d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5430-pull_request-952

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5400523&bid=17704503)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on bc1da568459aed6a8939eb8c6f6d363b5920b96b! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5432-pull_request-952

**Comment by adlerre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5400523&bid=17704503)

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on d50013b13ed8a4cbdfa90da7a5b2975fa73d3925! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5433-pull_request-952

**Comment by sebhofmann** [comment]
wrong branch name

**Pull request closed without merging**
