### PR TITLE
MCR-1776-move pi registration to a MCRJob

### PR DESCRIPTION
**Pull request by sebhofmann**

### CODE REVIEW

**Review by kkrebs — APPROVED** [review]
I tested functionality and it works, but we have now a problem if DOI registration fails. How can we inform user about this?

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 9b4385605bae0c37898dd82656f762f8e6cd2a9a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2618-pull_request-473

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4d56e2274662ee6cf9684b975f363c876a667610! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2622-pull_request-473

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4656b5bd75995e2496e3955b34346939b7a54f7e! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2697-pull_request-473

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 942ab14d81aec3e1e25d7ac0eb1e2a591c3e29ba! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2699-pull_request-473

**Comment by yagee-de** [comment]
There seems to be an issue with the permissions:
```
2018-03-01T13:51:17,491 INFO   MCRJobMaster: Creating:MCRJob [id:8.847, action:org.mycore.pi.MCRPIRegisterJobAction, status:PROCESSING, added:01.03.18 13:50, parameters:{action=REGISTER, registrationServiceID=Datacite, obj=dbt_mods_00032697, doi=10.5072/dbt.32697}]
2018-03-01T13:51:17,563 INFO   MCRXSLTransformer: Transformer lastModified: 1519907984000
2018-03-01T13:51:17,563 INFO   MCRXSLTransformer: Source lastModified     : 1519908617248
2018-03-01T13:51:17,564 INFO   MCRXSLTransformer: Start transforming: dbt_mods_00032697.xml
2018-03-01T13:51:17,572 WARN   MCRDOIRegistrationService: Found existing DOI(10.5072/dbt.32697) in Document will be replaced with 10.5072/dbt.32697
2018-03-01T13:51:19,284 INFO   MCRDataciteClient: application/pdf=https://www.db-thueringen.de/test/doi-test/servlets/MCRFileNodeServlet/dbt_derivate_00038864/microprofile.pdf
2018-03-01T13:51:19,569 INFO   MIRStrategy: Checking if dbt_mods_00032697 is in category mir_access:accessKey.
2018-03-01T13:51:19,588 ERROR  MCRJobThread: Exception occured while try to start job.2018-03-01T13:51:19,588 ERROR  MCRJobThread: Exception occured while try to start job.
org.mycore.common.MCRException: Could not update flags of object dbt_mods_00032697
	at org.mycore.pi.MCRPIRegistrationService.updateFlag(MCRPIRegistrationService.java:422)
	at org.mycore.pi.MCRPIJobRegistrationService.updateRegistrationDate(MCRPIJobRegistrationService.java:132)
	at org.mycore.pi.doi.MCRDOIRegistrationService.registerJob(MCRDOIRegistrationService.java:437)
	at org.mycore.pi.MCRPIJobRegistrationService.lambda$delegateAction$0(MCRPIJobRegistrationService.java:228)
	at org.mycore.pi.MCRPIJobRegistrationService.runAsJobUser(MCRPIJobRegistrationService.java:208)
	at org.mycore.pi.MCRPIJobRegistrationService.delegateAction(MCRPIJobRegistrationService.java:225)
	at org.mycore.pi.MCRPIRegisterJobAction.execute(MCRPIRegisterJobAction.java:51)
	at org.mycore.services.queuedjob.MCRJobThread.run(MCRJobThread.java:78)
	at org.mycore.util.concurrent.processing.MCRProcessableFactory$RunnableProgressableAdapter.call(MCRProcessableFactory.java:174)
	at org.mycore.util.concurrent.processing.MCRProcessableSupplier.get(MCRProcessableSupplier.java:96)
	at org.mycore.util.concurrent.MCRPrioritySupplier.get(MCRPrioritySupplier.java:49)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: MyCoRe Exception: org.mycore.access.MCRAccessException

Message:
You do not have the permission 'writedb' on 'dbt_mods_00032697' to perfom: Update object.

Stack trace:
org.mycore.access.MCRAccessException: You do not have the permission 'writedb' on 'dbt_mods_00032697' to perfom: Update object.
	at org.mycore.access.MCRAccessException.missingPermission(MCRAccessException.java:42)
	at org.mycore.datamodel.metadata.MCRMetadataManager.update(MCRMetadataManager.java:835)
	at org.mycore.datamodel.metadata.MCRMetadataManager.update(MCRMetadataManager.java:728)
	at org.mycore.pi.MCRPIRegistrationService.updateFlag(MCRPIRegistrationService.java:420)
	at org.mycore.pi.MCRPIJobRegistrationService.updateRegistrationDate(MCRPIJobRegistrationService.java:132)
	at org.mycore.pi.doi.MCRDOIRegistrationService.registerJob(MCRDOIRegistrationService.java:437)
	at org.mycore.pi.MCRPIJobRegistrationService.lambda$delegateAction$0(MCRPIJobRegistrationService.java:228)
	at org.mycore.pi.MCRPIJobRegistrationService.runAsJobUser(MCRPIJobRegistrationService.java:208)
	at org.mycore.pi.MCRPIJobRegistrationService.delegateAction(MCRPIJobRegistrationService.java:225)
	at org.mycore.pi.MCRPIRegisterJobAction.execute(MCRPIRegisterJobAction.java:51)
	at org.mycore.services.queuedjob.MCRJobThread.run(MCRJobThread.java:78)
	at org.mycore.util.concurrent.processing.MCRProcessableFactory$RunnableProgressableAdapter.call(MCRProcessableFactory.java:174)
	at org.mycore.util.concurrent.processing.MCRProcessableSupplier.get(MCRProcessableSupplier.java:96)
	at org.mycore.util.concurrent.MCRPrioritySupplier.get(MCRPrioritySupplier.java:49)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.mycore.access.MCRAccessException.missingPermission(MCRAccessException.java:42)
	at org.mycore.datamodel.metadata.MCRMetadataManager.update(MCRMetadataManager.java:835)
	at org.mycore.datamodel.metadata.MCRMetadataManager.update(MCRMetadataManager.java:728)
	at org.mycore.pi.MCRPIRegistrationService.updateFlag(MCRPIRegistrationService.java:420)
	... 14 more
```

**Review by Mewel — APPROVED** [review]
Seems to work with jportal.

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on d4c82affe24d6ab07cec19fb42d99885a05bc33d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/2893-pull_request-473

**Pull request merged**
