### PR TITLE
MCR-2361 add jersey-mvc-jsp to managed dependencies

### PR DESCRIPTION
**Pull request by rsteph-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2361).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e35b94940d008b2306475325452d8e432f86c43d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6668-pull_request-1190

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on e35b94940d008b2306475325452d8e432f86c43d! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/6668-pull_request-1190

**Comment by rsteph-de** [comment]
For main branch this was solved by  MCR-2360 update dependencies
(use of Jersey BOM manages all jersey dependencies).
But I still would like to see this fix in 2020.06LTS.

**Comment by sebhofmann** [comment]
run "mvn clean install -Pauto-update" to sort the pom.xml

**Comment by kkrebs** [comment]
please rebase

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
