### PR TITLE
MCR-2584 deprecate IFS1 clases

### PR DESCRIPTION
**Pull request by yagee-de**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2584).

### CODE REVIEW

**Comment by yagee-de** [comment]
@rsteph-de please go ahead and fix mycore-restapi v1 classes

**Review by rsteph-de — APPROVED** [review]
looks good for me

**Review by kkrebs — APPROVED** [review]

**Comment by kkrebs** [comment]
please check with UBO and MIR before merging. thanks!

**Review by sebhofmann — APPROVED** [review]

**Comment by yagee-de** [comment]
MIR compiles fine without changes

**Comment by yagee-de** [comment]
UBO compiles also, merging this PR then

**Pull request merged**
