### PR TITLE
MCR-2041 replace glyphicons with fa

### PR DESCRIPTION
**Pull request by kkrebs**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2041).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 17f1c5e4a50e60f16f835eae33a71221a3ac3c4c! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4715-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on cc2a0e8988bd47dd178ee0784d0532c13f8616c6! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4717-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on a5badf2cd6d41b49cc4bc9aca1e13473e27808f9! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4719-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 758a6e3bc705ea71c7e02bf6b607e2448ad02c8a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4727-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 758a6e3bc705ea71c7e02bf6b607e2448ad02c8a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4727-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on fbb4b976eb3d8b76274ae17c2923c790a2efe73a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4729-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on fbb4b976eb3d8b76274ae17c2923c790a2efe73a! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4729-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on fd20c33670f38ddde3ace062f6d7a82cb68ce490! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4731-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on fd20c33670f38ddde3ace062f6d7a82cb68ce490! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4731-pull_request-829

**Review by bt1cu — APPROVED** [review]

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on fd20c33670f38ddde3ace062f6d7a82cb68ce490! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4731-pull_request-829

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on fd20c33670f38ddde3ace062f6d7a82cb68ce490! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/4731-pull_request-829

**Pull request merged**
