### PR TITLE
MCR-3125 Set max length to MCRJob parameter value to 16384

### PR DESCRIPTION
**Pull request by Possommi**
[MCR-3125](https://mycore.atlassian.net/browse/MCR-3125).

[MCR-3125]: https://mycore.atlassian.net/browse/MCR-3125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sebhofmann — APPROVED** [review]

**Review by kkrebs — CHANGES_REQUESTED** [review]
need migration step, so this should be a change in main branch

**Comment by yagee-de** [comment]
MS SQL Server
> The ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them.

– [Source](https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver16)

**Comment by yagee-de** [comment]
Type „TEXT“ is also not part of SQL or JDBC standard – but present in many DBMS. So I would prefer to make reasonable big VARCHAR out of it. "columDefinition" also makes this not portable as this definition is used on every DBMS.

**Review by toKrause — APPROVED** [review]

**Review by toKrause — APPROVED** [review]

**Review by kkrebs — APPROVED** [review]

**Comment by kkrebs** [comment]
Please add migration documentation to https://www.mycore.de/documentation/migrate/migrate_mcr2024_06/

**Pull request merged**
