### PR TITLE
MCR-2553 Viewer can't display files with single quotes in file path

### PR DESCRIPTION
**Pull request by toKrause**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2553).

### CODE REVIEW

**Comment by sebhofmann** [comment]
Better use the method [jQuery.escapeSelector](https://api.jquery.com/jQuery.escapeSelector/) for this.
There are also other places where the name needs to be escaped. I can do that later.

**Comment by toKrause** [comment]
> Better use the method [jQuery.escapeSelector](https://api.jquery.com/jQuery.escapeSelector/) for this.

Yes, I know, couldn't get it to work in the TypeScript file though. Presumably some import is needed. Feel free to edit.

**Comment by sebhofmann** [comment]
Is the filepath even assigned to the thumbnail-id? The ID is read from mets (its a ncname) or its a page number from PDF and both should not contain any Symbols which need to be escaped.

**Comment by toKrause** [comment]
I don't know what exactly is happening. I didn't try to understand the whole code. I can only say that the viewer doesn't work, unless both modifications are made.

**Comment by toKrause** [comment]
Closed in favor of https://github.com/MyCoRe-Org/mycore/pull/1445

**Pull request closed without merging**
