### PR TITLE
MCR-2404 fixed thumbnail exception

### PR DESCRIPTION
**Pull request by rsteph-de**
closed outputstream an modified delete code

[Link to jira](https://mycore.atlassian.net/browse/MCR-2404).

### CODE REVIEW

**Review by sebhofmann — CHANGES_REQUESTED** [review]
If mcrImage.tile(); throws an error, then the file will not be deleted.

**Comment by rsteph-de** [comment]
> 
> 
> If mcrImage.tile(); throws an error, then the file will not be deleted.

Fixed by adding a try-catch block

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 0be61ee8a63cbb2d01e915a6cf34bef8150c88f8! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/7118-pull_request-1237

**Review by kkrebs — APPROVED** [review]

**Comment by kkrebs** [comment]
Because this fixes the error I merged this. For a perhaps better solution we had opened a new ticket https://mycore.atlassian.net/browse/MCR-2409

**Pull request merged**
