### PR TITLE
MCR-2270 mods implementation for mycore-csl

### PR DESCRIPTION
**Pull request by sebhofmann**
[Link to jira](https://mycore.atlassian.net/browse/MCR-2270).

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 28ae388ff271ccfb5f90af5b28a7c544389b688f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5950-pull_request-1054

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 49a74727ff1d28f409ed221d4c93c92039279066! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5952-pull_request-1054

**Comment by yagee-de** [comment]
Please use Code-Format and Copyright Header

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 4740f73d667e06357bdf5a0f1797a13a660dd60f! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/5954-pull_request-1054

**Comment by fluetze** [comment]
Proposal: The genre mapping should be done via classification mapping. There could be a default if no mapping is given.

**Comment by fluetze** [comment]
` idb.numberOfPages(String.valueOf(Integer.parseInt(end)-Integer.parseInt(start)));`
will throw an Exception if page number is not numeric. Some journals use non-numeric page numbers.

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
