### PR TITLE
MCR-1534 Do not reuse deleted MCRObjectIDs

### PR DESCRIPTION
**Pull request by yagee-de**

### CODE REVIEW

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 584a700012dfe301e4e719ac952e2152b085d0f5! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1727-pull_request-296

**Review by kkrebs — CHANGES_REQUESTED** [review]
This doesn't work. If I use MIR with this branch, create an object, delete this and restarts the application, I can create a new object with the same ID. Here is my database content:

          1 c         mir_mods_00000355 2017-06-19 10:28:36.565 administrator 0:0:0:0:0:0:0:1
          2 d         mir_mods_00000355 2017-06-19 10:34:27.915 administrator 0:0:0:0:0:0:0:1
         33 c         mir_mods_00000355 2017-06-19 10:52:59.711 administrator 0:0:0:0:0:0:0:1
         34 d         mir_mods_00000355 2017-06-19 10:52:59.718 administrator 0:0:0:0:0:0:0:1

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on 627392c1d46eab04b20b1343a4bb79c4c79f732b! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1761-pull_request-296

**Comment by MyCoRe-Travis** [comment]
Something gone wrong on d4fcb46315423b7680ff18939db18c422cc54876! 
 Please Check https://github.com/MyCoRe-Travis/test_artifacts/tree/1763-pull_request-296

**Review by kkrebs — APPROVED** [review]

**Pull request merged**
