### PR TITLE
MCR-3024 Some command cronjobs need to be performed with more privileges

### PR DESCRIPTION
**Pull request by toKrause**
[Link to jira](https://mycore.atlassian.net/browse/MCR-3024).

**Depends on https://github.com/MyCoRe-Org/mycore/pull/2045!**

### CODE REVIEW

**Comment by sebhofmann** [comment]
I have a similar functionality in MCRPI (org.mycore.pi.MCRPIJobService#runAsJobUser) it would be good, if they work like the same for the user who configures it. The newly added function only works for the system user instances and the old code from me only works for real users in the database and falls back to the janitor. 
Since this goes in to main, it would be cool if they both support all user types and maybe share the code for getting the user information.

**Comment by toKrause** [comment]
I've implemented a reusable and extendable mechanism to store references to arbitrary user information in [MCR-3027](https://mycore.atlassian.net/browse/MCR-3027) (with implementations for system users and database stored users) and used that feature in the PR.

References would be stored in configuration values as, for example, `system:JANITOR`, `user:foo` or `user:foo@ldap`.

This PR now depends on https://github.com/MyCoRe-Org/mycore/pull/2045.

[MCR-3027]: https://mycore.atlassian.net/browse/MCR-3027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by toKrause** [comment]
You could reuse the feature from [MCR-3027](https://mycore.atlassian.net/browse/MCR-3027) by replacing `MCRUser user = MCRUserManager.getUser(jobUser);` with `MCRUserInformation user = MCRUserInformationResolver.instance().getOrThrow(jobUser);` and changing , for example, `MCR.PI.Service.Datacite.JobApiUser=administrator` to `MCR.PI.Service.Datacite.JobApiUser=user:administrator`. If you do this, the necessary changes to already configured jobs should be documented as a migration step when updating from 2023.06 to 2024.06. 

[MCR-3027]: https://mycore.atlassian.net/browse/MCR-3027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by sebhofmann — DISMISSED** [review]
Changes in [MCRCommandCronJob.java](https://github.com/MyCoRe-Org/mycore/pull/2041/files#diff-b1ba63446aea32ae808e0bbc488b0b642c1416c37926c951b35098cd6b41d1cf) look good.

**Comment by sebhofmann** [comment]
Rebase please

**Review by sebhofmann — APPROVED** [review]

**Pull request merged**
